# Generated by Django 4.2.1 on 2023-06-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.source_category'),
        ),
    ]
