# Generated by Django 4.2.1 on 2023-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_source_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='source_category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
